# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &thuyen20004fdffdf
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: thuyen20004fdffdfMSP

        # ID to load the MSP definition as
        ID: thuyen20004fdffdfMSP

        MSPDir: ../organizations/peerOrganizations/thuyen20004fdffdf.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('thuyen20004fdffdfMSP.admin', 'thuyen20004fdffdfMSP.peer', 'thuyen20004fdffdfMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('thuyen20004fdffdfMSP.admin', 'thuyen20004fdffdfMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('thuyen20004fdffdfMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('thuyen20004fdffdfMSP.peer')"
