# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &435453
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: 435453MSP

        # ID to load the MSP definition as
        ID: 435453MSP

        MSPDir: ../organizations/peerOrganizations/435453.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('435453MSP.admin', '435453MSP.peer', '435453MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('435453MSP.admin', '435453MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('435453MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('435453MSP.peer')"
